### ISSUE TITLE
Magento 2 > Payment Method Not Showing Up in Admin

### ISSUE THREAD

**Issue by shadowcomm** [SpectroCoin/Magento-2-Bitcoin-Payment-Gateway-Extension#1]
Hi, I have followed the instructions to install the Magento 2 extension, but when I log into the backed and try to enable the payment method, the module is not showing. I have cleared the cache, deployed static files, re-indexed etc. and I am still not able to get it to show up. 

Any advice you may have would be most appreciated. 

-ShadowComm

**Comment by ktamasauskas** [comment]
Hello, please contact us directly via email: merchant@spectrocoin.com and we will solve your problem.
